add functions to auto_tmux and tat

diff --git a/home-manager/tmux/tat b/home-manager/tmux/tat
--- a/home-manager/tmux/tat
+++ b/home-manager/tmux/tat
@@ -25,24 +25,38 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 
-path_name="$(basename "$PWD" | tr . -)"
-session_name=${1-$path_name}
+if [ -n "$1" ]; then
+  if [ -d "$1" ]; then
+    target_dir="$1"
+  else
+    echo "Error: '$1' is not a valid directory."
+    exit 1
+  fi
+else
+  target_dir="$PWD"
+fi
+
+session_name="$(basename "$target_dir" | tr . -)"
 
 not_in_tmux() {
   [ -z "$TMUX" ]
 }
 
 session_exists() {
-  tmux list-sessions | sed -E 's/:.*$//' | grep -q "^$session_name$"
+  tmux has-session -t "$session_name" 2>/dev/null
 }
 
 create_detached_session() {
-  (TMUX='' tmux new-session -Ad -s "$session_name")
+  TMUX='' tmux new-session -Ad -s "$session_name" -c "$target_dir"
 }
 
 create_if_needed_and_attach() {
   if not_in_tmux; then
-    tmux new-session -As "$session_name"
+    if session_exists; then
+      tmux attach-session -t "$session_name"
+    else
+      tmux new-session -As "$session_name" -c "$target_dir"
+    fi
   else
     if ! session_exists; then
       create_detached_session
